In [5]:
import numpy as np
from keras import Sequential
from keras.layers import SimpleRNN, Dense

In [10]:
model = Sequential()
model.add(SimpleRNN(3, input_shape = (4, 5)))
model.add(Dense(1, activation='sigmoid'))

c:\Users\HP\OneDrive\Desktop\ML-DS\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [11]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)        │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.get_weights()[0]

array([[-0.04382157,  0.27490932, -0.5777769 ],
       [ 0.03400707,  0.43282193, -0.35611898],
       [-0.43748003,  0.21669275,  0.86239964],
       [-0.59987855,  0.83265036,  0.2125048 ],
       [ 0.18698758,  0.73792595,  0.25911087]], dtype=float32)

In [17]:
model.get_weights()[1]

array([[ 0.25263917,  0.03343295,  0.9669826 ],
       [ 0.8681819 , -0.44901192, -0.21130168],
       [-0.42712235, -0.8929    ,  0.14246407]], dtype=float32)

In [18]:
model.get_weights()[2]

array([0., 0., 0.], dtype=float32)