## Basics Of Numpy

numpy is used for performing mathematical operations on arrays as they are very oprtimised, fast and efficient as compared to list in python

### Import Numpy 

In [6]:
import numpy as np

### Creating first array

In [17]:
arr = np.array([1,2,3,4]) #1D array
print(arr)

matrix = np.array([[1,2,3], [4,5,6]]) # 2D array
print(matrix)

tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #nD array
# print(tensor)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


### Numpy Array VS Python Lists

In [16]:
import time 
start_time = time.time()

python_list = [x*2 for x in range(1,100000000)]
print("time taken", time.time() - start_time)

start_time = time.time()
python_array = np.arange(0,100000000)
python_array = python_array * 2
print(time.time() - start_time)

time taken 28.585803270339966
0.9527871608734131


Python lists are very slow as compared to numpy arrays 

### properties of arrays in numpy

In [ ]:
print(arr.shape) #shape of the array
print(arr.ndim) #Dimension of the array
print(arr.size) # Number of elements in the array

(4,)
1
4


### various ways of creating array in numpy

In [13]:
zeroes_array = np.zeros((2,3))
print(zeroes_array)

ones_array = np.ones((2,3))
print(ones_array)

array_with_range = np.arange(0,10)
print(array_with_range) 

array_with_constants = np.full((2,3), 3)
print(array_with_constants)

array_with_randoms = np.random.random((2,4))
print(array_with_randoms)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[[3 3 3]
 [3 3 3]]
[[0.98337018 0.9306927  0.6369306  0.95150123]
 [0.1823763  0.11735361 0.76603109 0.18686345]]
