### Operations on arrays in numpy

In [1]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape((2,3)) # changes the shape of the original array
arr.resize((2,3)) # don't modify the original array returns a new array 
print(arr)
print(new_arr)

flattend_array = new_arr.flatten()
print(flattend_array)

# ADDITION IN ARRAYS
array_2 = np.arange(1,11)
array_2 = array_2 + 3
print(array_2)

# MULTIPLICATION IN ARRAYS
array_3 = np.arange(1,11)
array_3 = array_3 * 2
print(array_3)

# TRANSPOSE OF MATRIX
matrix = np.array([[1,2],[3,4],[4,5]])
transpose = matrix.T
print(transpose)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[ 4  5  6  7  8  9 10 11 12 13]
[ 2  4  6  8 10 12 14 16 18 20]
[[1 3 4]
 [2 4 5]]


In [39]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array[0])
print(array[0:3])
print(array[-1])

array_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("3rd Element of 1st row is :", array_2D[0,2])

print("1st row of 2D array is:", array_2D[0, :])
print("1st col of the 2D array is :", array_2D[:, 0])


1
[1 2 3]
10
3rd Element of 1st row is : 3
1st row of 2D array is: [1 2 3]
1st col of the 2D array is : [1 4 7]


### Sorting


In [42]:
array = np.random.random((1,9))
print(array)
sorted_array = np.sort(array)
print(sorted_array)

matrix = np.array([[1,2],[3,4],[4,5]])
sorted_matrix_by_col = np.sort(matrix, axis=0)
sorted_matrix_by_row = np.sort(matrix, axis=1)

print(sorted_matrix_by_col)
print(sorted_matrix_by_row)

[[0.55160042 0.24718164 0.61707335 0.9887134  0.13196111 0.81803332
  0.82366852 0.28866214 0.79046198]]
[[0.13196111 0.24718164 0.28866214 0.55160042 0.61707335 0.79046198
  0.81803332 0.82366852 0.9887134 ]]
[[1 2]
 [3 4]
 [4 5]]
[[1 2]
 [3 4]
 [4 5]]


### Masking and Filtering

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
filtered_array = array[array % 2 == 0] #filtering
print(filtered_array)

mask = array % 2 == 0
print(mask)
filter_by_mask = array[mask] #Filtering by Mask
print(filter_by_mask)

where_array = np.where(array % 2 == 0, 0, array)
print(where_array)

[ 2  4  6  8 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
[1 0 3 0 5 0 7 0 9 0]
