### operations on real Data Set

we have this data of 8 students having some marks in 5 subjects

In [1]:
import numpy as np

np.random.seed(42)  # reproducibility
marks = np.random.randint(40, 101, size=(8, 5))  # 40–100 inclusive

print("Marks (rows = students, cols = subjects):\n", marks)

Marks (rows = students, cols = subjects):
 [[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]
 [ 69  77  41  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]]


### Basic Mathematical operations

In [5]:
# Finding total, average, maximum marks of each student 
total_mark_array = np.sum(marks[:, :], axis=1)
print(total_mark_array)

average_marks_array = np.mean(marks[:, :], axis=1)
print(average_marks_array)

maximum_marks = np.max(total_mark_array)
print(maximum_marks)

[373 382 283 351 340 346 381 399]
[74.6 76.4 56.6 70.2 68.  69.2 76.2 79.8]
399


In [10]:
#  finding highest lowest and average marks of each subject
highest_marks_array = np.max(marks[:, :], axis=0)
print(highest_marks_array)

lowest_marks_array = np.min(marks[:, :], axis=0)
print(lowest_marks_array)

average_marks_per_subject = np.mean(marks[:, :], axis=0)
print(average_marks_per_subject)

hardest_subject = np.min(average_marks_per_subject)
print(hardest_subject)


[ 92 100  97  99 100]
[47 51 41 50 42]
[70.    76.5   65.5   66.75  78.125]
65.5


### Filtering and Masking

In [19]:
# filtering and searching

class_average = np.mean(marks)
# print(class_average)

for i in marks: 
    for j in i:
        if j > 91:
            print(i)
            break

print("\n\n")
# score less than 50 in all subjects
for i in marks:
    flag = False
    for j in i:
        if j > 50: 
            flag = True
            break
    if flag == False:
        print (i)

# stdent whose average is above averge of the class
student_average = np.mean(marks[:, :], axis=1)
mask = student_average > class_average

above_average_students = student_average[mask]
print(above_average_students)
            

[ 47 100  60  78  97]
[92 75 79 63 42]
[61 92 41 63 83]
[69 77 41 99 60]
[ 72  51  97  61 100]
[83 64 88 66 98]



[74.6 76.4 76.2 79.8]


### Indexing And Slicing

In [24]:
#  Marks of first 2 students
marks_of_2_students = marks[:2, :]
print(marks_of_2_students)

marks_of_maths = marks[:, 0]
print(marks_of_maths)

# Marks of 2nd and 4th student only
marks_of_2nd_students = marks[2, :]
marks_of_4th_students = marks[4, :]

print(marks_of_2nd_students)
print(marks_of_4th_students)

[[ 78  91  68  54  82]
 [ 47 100  60  78  97]]
[78 47 58 92 61 69 72 83]
[58 62 50 50 63]
[61 92 41 63 83]
