In [ ]:
import torch

In [ ]:
x = torch.tensor(2.3, requires_grad=True)
y = x**2

In [ ]:
x

tensor(2.3000, requires_grad=True)

In [ ]:
y

tensor(5.2900, grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(4.6000)

In [ ]:
x = torch.rand(3, requires_grad=True)

In [ ]:
x

tensor([0.3746, 0.9672, 0.1605], requires_grad=True)

In [ ]:
y = (x**2).mean()

In [ ]:
y

tensor(0.3672, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([0.2497, 0.6448, 0.1070])

In [ ]:
x = torch.rand(4, requires_grad=True)

In [ ]:
y = x + 2
y

tensor([2.3689, 2.2929, 2.4611, 2.2532], grad_fn=<AddBackward0>)

In [ ]:
z = torch.sigmoid(y)

In [ ]:
z

tensor([0.9144, 0.9083, 0.9214, 0.9049], grad_fn=<SigmoidBackward0>)

In [ ]:
x.grad

In [ ]:
x

tensor([0.3689, 0.2929, 0.4611, 0.2532], requires_grad=True)

In [ ]:
y

tensor([2.3689, 2.2929, 2.4611, 2.2532], grad_fn=<AddBackward0>)

In [ ]:
y = torch.rand(3, requires_grad=True)

In [ ]:
y

tensor([0.6299, 0.6367, 0.9641], requires_grad=True)

In [ ]:
y.requires_grad_(False)

tensor([0.6299, 0.6367, 0.9641])

In [ ]:
y

tensor([0.6299, 0.6367, 0.9641])

In [ ]:
y = torch.rand(3, requires_grad=True)

In [ ]:
y.