## **Tensors**   
 Tensors are Multidimensional Arrays

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.9.0+cu126


In [ ]:
if(torch.cuda.is_available()):
    print("GPU is available")
    print(f" using {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")


GPU is available
 using Tesla T4


In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.6726, 0.5740, 0.9233],
        [0.9178, 0.7590, 0.7775]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[214748364844, 219043332140, 188978561117],
        [223338299483, 227633266732, 231928234028]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

# negative
torch.neg(c)

#round
torch.round(c)

#ceil
torch.ceil(c)

# floor
torch.floor(c)



tensor([ 1, -2,  3, -4])

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

# max and min
torch.max(e)
torch.min(e)

# product
torch.prod(e)

# standard deviation
torch.std(e)

# variance
torch.var(e)

# argmax
torch.argmax(e)

# argmin
torch.argmin(e)

tensor(2)

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[68, 56],
        [36,  0]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(-34.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.2647,  0.3235, -0.1176],
        [ 1.0882, -0.4412, -0.2941],
        [-1.0588,  0.2941,  0.5294]])

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[False,  True, False],
        [ True, False, False]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6726, 0.5740, 0.9233],
        [0.9178, 0.7590, 0.7775]])
tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])


In [ ]:
m.add_(n)

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [ ]:
m

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [ ]:
n

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])

In [ ]:
torch.relu(m)

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [ ]:
m.relu_()

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [ ]:
m

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [ ]:
b

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [ ]:
id(a)

132170778146720

In [ ]:
id(b)

132170778146720

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [ ]:
b

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.3451,  0.0453],
        [ 0.9798,  0.5548,  0.6868]])

In [ ]:
b

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [ ]:
id(a)

132170778146720

In [ ]:
id(b)

132170777661344